"""
Django settings for artdios project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
from decouple import config
import os
import mimetypes
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-h7ika^s(k9r*-$9^i9queb)*alj^bfzrww+)=h(=4=8u94kh-l"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '91.200.150.41', 'artdios.ru', 'www.artdios.ru']

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

mimetypes.add_type("application/javascript", ".js", True)
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "corsheaders",
    "debug_toolbar",
    "store.apps.StoreConfig",
    "notifications.apps.NotificationsConfig",
    "django_celery_results",
    "cacheops",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "csp.middleware.CSPMiddleware",
]

ROOT_URLCONF = "artdios.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'store', 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "artdios.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

CORS_ALLOW_CREDENTIALS = True


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:8000",
    "http://localhost:3000",
]

CSRF_TRUSTED_ORIGINS = ['http://localhost:5173', "http://localhost:3000",]


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEBUG_TOOLBAR_CONFIG = {
    "INTERCEPT_REDIRECTS": False,
    'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
}

INTERNAL_IPS = ['127.0.0.1', '91.200.150.41']


CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

CSP_DEFAULT_SRC = ("'self'")
CSP_SCRIPT_SRC = ("'self'",  "http://localhost:8000", "http://localhost:3000")
CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com")
CSP_IMG_SRC = ("'self'", "http://localhost:8000")
CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com", "http://localhost:8000")
CSP_CONNECT_SRC = ("'self'", "http://localhost:8000", "http://localhost:3000") 
CSP_OBJECT_SRC = ("'none'",)
CSP_FRAME_SRC = ("'self'",)
CSP_FRAME_ANCESTORS = ("'self'",)


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}


CACHEOPS = {
    'store.Product': {
        'ops': 'all',
        'timeout': 60 * 5,
        'tags': ['product_cache'],
    },
    'store.ProductType': {
        'ops': 'all',
        'timeout': 30 * 24 * 60 * 60,
        'tags': ['product_type_cache'],
    },
    'store.Category': {
        'ops': 'all',
        'timeout': 10 * 24 * 60 * 60,
        'tags': ['category_cache'],
    },
    'store.SubCategory': {
        'ops': 'all',
        'timeout': 10 * 24 * 60 * 60,
        'tags': ['subcategory_cache'],
    },
    'store.Characteristic': {
        'ops': 'all',
        'timeout': 60 * 5,
        'tags': ['characteristic_cache'],
    },
    'store.Promotion': {
        'ops': 'all',
        'timeout': 10 * 24 * 60 * 60,
        'tags': ['promotion_cache'],
    },
    'store.PopularProduct': {
        'ops': 'all',
        'timeout': 10 * 24 * 60 * 60,
        'tags': ['pop_product_cache'],
    },
    'store.Gallery': {
        'ops': 'all',
        'timeout': 10 * 24 * 60 * 60,
        'tags': ['gallery_cache'],
    },
    'store.WorkingHours': {
        'ops': 'all',
        'timeout': 30 * 24 * 60 * 60,
        'tags': ['working_hours_cache'],
    },
    'store.Phone': {
        'ops': 'all',
        'timeout': 30 * 24 * 60 * 60,
        'tags': ['phone_cache'],
    },
    'store.Email': {
        'ops': 'all',
        'timeout': 30 * 24 * 60 * 60,
        'tags': ['email_cache'],
    },
    'store.Address': {
        'ops': 'all',
        'timeout': 30 * 24 * 60 * 60,
        'tags': ['address_cache'],
    },
    
}