# Generated by Django 5.0.7 on 2024-07-18 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_panel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_show", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ProductType",
                "verbose_name_plural": "ProductTypes",
            },
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Address", "verbose_name_plural": "Address"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="characteristic",
            options={
                "verbose_name": "Characteristic",
                "verbose_name_plural": "Characteristics",
            },
        ),
        migrations.AlterModelOptions(
            name="contacts",
            options={"verbose_name": "Contacts", "verbose_name_plural": "Contacts"},
        ),
        migrations.AlterModelOptions(
            name="email",
            options={"verbose_name": "Email", "verbose_name_plural": "Emails"},
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "Gallery", "verbose_name_plural": "Gallery"},
        ),
        migrations.AlterModelOptions(
            name="phone",
            options={"verbose_name": "Phone", "verbose_name_plural": "Phones"},
        ),
        migrations.AlterModelOptions(
            name="popularproduct",
            options={
                "verbose_name": "PopularProduct",
                "verbose_name_plural": "PopularProducts",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={"verbose_name": "Promotion", "verbose_name_plural": "Promotions"},
        ),
        migrations.RemoveField(
            model_name="category",
            name="discount",
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="client_panel.producttype",
            ),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_show", models.BooleanField(default=True)),
                ("discount", models.IntegerField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="client_panel.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "SubCategory",
                "verbose_name_plural": "SubCategories",
                "indexes": [
                    models.Index(fields=["name"], name="client_pane_name_3afc02_idx"),
                    models.Index(
                        fields=["is_show"], name="client_pane_is_show_d5ce17_idx"
                    ),
                ],
            },
        ),
    ]
