# Generated by Django 5.0.7 on 2024-07-18 11:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_category_slug_gallery_slug_product_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, null=True, populate_from="name"
            ),
        ),
    ]
