# Generated by Django 5.0.7 on 2024-07-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_gallery_slug_alter_product_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="contacts",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="address",
                to="store.contacts",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="contacts",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="email",
                to="store.contacts",
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="contacts",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="phone",
                to="store.contacts",
            ),
        ),
    ]
