# Generated by Django 5.0.7 on 2024-07-20 09:59

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_address_contacts_alter_email_contacts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="second_image",
            field=models.ImageField(null=True, upload_to=store.models.upload_products),
        ),
        migrations.AddField(
            model_name="product",
            name="third_image",
            field=models.ImageField(null=True, upload_to=store.models.upload_products),
        ),
    ]
