# Generated by Django 5.0.7 on 2024-07-24 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_alter_product_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contacts",
            new_name="WorkingHours",
        ),
        migrations.AlterModelOptions(
            name="workinghours",
            options={
                "verbose_name": "WorkingHours",
                "verbose_name_plural": "WorkingHours",
            },
        ),
        migrations.RemoveField(
            model_name="address",
            name="contacts",
        ),
        migrations.RemoveField(
            model_name="email",
            name="contacts",
        ),
        migrations.RemoveField(
            model_name="phone",
            name="contacts",
        ),
    ]
