# Generated by Django 5.0.7 on 2024-08-06 13:57

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_alter_subcategory_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="second_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.upload_products
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="third_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.upload_products
            ),
        ),
    ]
