# Generated by Django 5.0.7 on 2024-08-07 16:03

import store.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_alter_product_second_image_alter_product_third_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                max_length=300, upload_to=store.utils.upload_products
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="second_image",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=store.utils.upload_products,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="third_image",
            field=models.ImageField(
                blank=True,
                max_length=300,
                null=True,
                upload_to=store.utils.upload_products,
            ),
        ),
    ]
