# Generated by Django 5.0.7 on 2024-08-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_alter_product_image_alter_product_second_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="characteristics",
            field=models.ManyToManyField(
                related_name="products", to="store.characteristic"
            ),
        ),
    ]
