# Generated by Django 5.0.7 on 2024-08-16 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_product_characteristics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="characteristics",
        ),
    ]
