server {
    listen 80;
    server_name artdios.ru www.artdios.ru;
    return 301 https://$host$request_uri;
}

server {
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        server_name artdios.ru www.artdios.ru 91.200.150.41;
        ssl_certificate /etc/ssl/certs/artdios.crt;
        ssl_certificate_key /etc/ssl/private/artdios.key;

        root /var/www/artdios/frontend/dist;
        index index.html index.htm;

        location ~ /static/(.+) {
           alias /var/www/artdios/backend/staticfiles/$1;
        }

        location ~ ^/(?!(api-rest|control-panel)/).*$ {
           try_files $uri /index.html =404;
        }

        location ~ ^/api-rest/(?!media/) {
          rewrite ^/api-rest/(.*)$ /$1 break;
          proxy_pass http://localhost:8000;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location ~ ^/api-rest/media/(.*)$ {
          alias /var/www/artdios/backend/media/$1;
        }

        location /control-panel/ {
          proxy_pass http://localhost:8000/control-panel/;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

  error_log /var/log/nginx/artdios_error.log;

}
